package com.bookitng.bookitng.utils

object Constants {

    const val LOGGED_IN  = "LOGGED_IN"
    const val SPLASH_DELAY_CONFIG = 1500
    const val CURRENT_ACTIVE = "CURRENT ACTIVE"
    const val MAIN_MENU_FRAGMENT = "MAIN_MENU_FRAGMENT"
    const val FLIGHTS_FRAGMENT = "FLIGHTS_FRAGMENT"
    const val HOTELS_FRAGMENT = "HOTELS_FRAGMENT"
    const val VACATIONS_FRAGMENT = "VACATIONS_FRAGMENT"
    const val BUSES_FRAGMENT = "BUSES_FRAGMENT"
    const val BUS_LISTING_FRAGMENT = "BUS_LISTING_FRAGMENT"
    const val BUS_FARE_FRAGMENT = "BUS_FARE_FRAGMENT"
    const val BUS_PAYMENT_FRAGMENT = "BUS_PAYMENT_FRAGMENT"
    const val ENTERTAINMENT_FRAGMENT = "ENTERTAINMENT_FRAGMENT"
    const val USER_PROFILE_FRAGMENT = "USER_PROFILE_FRAGMENT"
}